# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import new_route_guide_pb2 as new__route__guide__pb2


class RouteGuideStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListAccounts = channel.unary_stream(
                '/routeguide.RouteGuide/ListAccounts',
                request_serializer=new__route__guide__pb2.Text.SerializeToString,
                response_deserializer=new__route__guide__pb2.Text.FromString,
                )
        self.ReceiveMessages = channel.unary_stream(
                '/routeguide.RouteGuide/ReceiveMessages',
                request_serializer=new__route__guide__pb2.Text.SerializeToString,
                response_deserializer=new__route__guide__pb2.Note.FromString,
                )
        self.SendMessage = channel.stream_stream(
                '/routeguide.RouteGuide/SendMessage',
                request_serializer=new__route__guide__pb2.Note.SerializeToString,
                response_deserializer=new__route__guide__pb2.Note.FromString,
                )


class RouteGuideServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListAccounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouteGuideServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListAccounts': grpc.unary_stream_rpc_method_handler(
                    servicer.ListAccounts,
                    request_deserializer=new__route__guide__pb2.Text.FromString,
                    response_serializer=new__route__guide__pb2.Text.SerializeToString,
            ),
            'ReceiveMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.ReceiveMessages,
                    request_deserializer=new__route__guide__pb2.Text.FromString,
                    response_serializer=new__route__guide__pb2.Note.SerializeToString,
            ),
            'SendMessage': grpc.stream_stream_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=new__route__guide__pb2.Note.FromString,
                    response_serializer=new__route__guide__pb2.Note.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'routeguide.RouteGuide', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RouteGuide(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/routeguide.RouteGuide/ListAccounts',
            new__route__guide__pb2.Text.SerializeToString,
            new__route__guide__pb2.Text.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReceiveMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/routeguide.RouteGuide/ReceiveMessages',
            new__route__guide__pb2.Text.SerializeToString,
            new__route__guide__pb2.Note.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMessage(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/routeguide.RouteGuide/SendMessage',
            new__route__guide__pb2.Note.SerializeToString,
            new__route__guide__pb2.Note.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
