# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: new_route_guide.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15new_route_guide.proto\x12\nrouteguide\"\x14\n\x04Text\x12\x0c\n\x04text\x18\x01 \x01(\t\"J\n\x04Note\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x11\n\trecipient\x18\x02 \x01(\t\x12\x0e\n\x06length\x18\x03 \x01(\x03\x12\x0f\n\x07message\x18\x04 \x01(\t2\xb8\x01\n\nRouteGuide\x12\x36\n\x0cListAccounts\x12\x10.routeguide.Text\x1a\x10.routeguide.Text\"\x00\x30\x01\x12\x39\n\x0fReceiveMessages\x12\x10.routeguide.Text\x1a\x10.routeguide.Note\"\x00\x30\x01\x12\x37\n\x0bSendMessage\x12\x10.routeguide.Note\x1a\x10.routeguide.Note\"\x00(\x01\x30\x01\x42\x36\n\x1bio.grpc.examples.routeguideB\x0fRouteGuideProtoP\x01\xa2\x02\x03RTGb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'new_route_guide_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.routeguideB\017RouteGuideProtoP\001\242\002\003RTG'
  _TEXT._serialized_start=37
  _TEXT._serialized_end=57
  _NOTE._serialized_start=59
  _NOTE._serialized_end=133
  _ROUTEGUIDE._serialized_start=136
  _ROUTEGUIDE._serialized_end=320
# @@protoc_insertion_point(module_scope)
